sales_analysis/analytics/urls.py
from django.urls import path, include
from .views import (
    home,
    upload_file,
    process_file,
    register,
    dashboard,
    select_headers,
    charts,
    share_chart,
    view_shared_chart,
    CustomPasswordResetConfirmView,
)
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),
    path('signup/', register, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('upload/', upload_file, name='upload'),
    path('process_file/<int:file_id>/', process_file, name='process_file'),
    path('select/<int:file_id>/', select_headers, name='select'),
    path('charts/<int:file_id>/', charts, name='charts'),
    path('dashboard/<int:file_id>/', dashboard, name='dashboard'),
    path('share_chart/<int:file_id>/<str:chart_type>/', share_chart, name='share_chart'),
    path('password_reset/', include('django.contrib.auth.urls')), 
    path('accounts/password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('analytics/shared_charts/<str:chart_id>/<str:chart_type>/', view_shared_chart, name='view_shared_chart'),
    
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_analysis/sales_analysis/urls.py
from django.contrib import admin
from django.urls import path, include
from analytics.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),  
    path('analytics/', include('analytics.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 



]
if settings.DEBUG:  # Only serve media files in development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_analysis/analytics/models.py
from django.db import models
from django.contrib.auth.models import User

class SalesData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to='sales_data/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


class SharedChart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file_id = models.IntegerField()
    chart_type = models.CharField(max_length=50)
    unique_id = models.CharField(max_length=8, unique=True)  # Ensure this is unique

    def __str__(self):
        return f"{self.chart_type} shared by {self.user.username}"
    

sales_analysis/sales_analysis/views.py
from django.shortcuts import render
from django.http import JsonResponse


def home_page_view(request):
    return JsonResponse({'message': 'OK'})

sales_analysis/sales_analysis/templates/base_generic.html
{% load static %}
<!doctype HTML>
<html lang="en">
    <head>
        <title>{% block title %}Data Vis{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Основу макета составляет большой экран Jumbotron и базовая система разметки. В панель навигации включены поля формы.">
        <meta name="author" content="">

        <link rel="icon" type="image/x-icon" href="{% static 'images/logo2.png' %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

        <link href="jumbotron.css" rel="stylesheet">

        <button id="shareChartButton" onclick="shareChart('line', 3)">Share Chart</button>

        <!-- Modal for Share Link -->
        <div id="shareLinkModal" style="display: none;">
            <div class="modal-content">
                <span class="close" onclick="closeModal()">&times;</span>
                <h2>Share Your Chart</h2>
                <p id="shareLinkText"></p>
                <button onclick="copyToClipboard()">Copy Link</button>
            </div>
        </div>
    
        
        <style>
            .jumbotron {
                padding: 2rem 1rem;
                margin-bottom: 1rem;
                border-radius: 0.3rem;
                height: 90vh;
            }
            
            footer {
                padding: 5px 0; /* Reduced padding */
                text-align: center;
                font-size: 0.9em; /* Optional: smaller font size */
            }

            
            .footer-container {
                padding: 5px; /* Adjust padding to control space */
                height: 30px; /* Set a fixed height */
                overflow: hidden; /* Hide any overflow content */
                display: flex; /* Use flexbox for alignment */
                align-items: center; /* Center items vertically */
                justify-content: center; /* Center items horizontally */
            }
            .graph-container-wrapper {
                display: flex;
                justify-content: center;
                flex-direction: column;
                align-items: center;
                margin-bottom: 20px;
            }
        
            .graph-container {
                display: none; /* Hide all graphs initially */
                width: 100%; /* Full width */
                max-width: 1200px; /* Set a maximum width */
                margin: auto; /* Center the container horizontally */
            }
        
            .button-container {
                display: flex; 
                justify-content: center; 
                margin-bottom: 20px; 
            }
        
            .button-pressed {
                background-color: darkorange !important; 
                color: white; 
            }
        
            .message-list {
                list-style-type: none;
                padding: 0;
            }
        
            .alert {
                padding: 15px;
                margin-bottom: 20px;
                border: 1px solid transparent;
                border-radius: 4px;
            }
        
            .alert-danger {
                color: #721c24;
                background-color: #f8d7da;
                border-color: #f5c6cb;
            }
        
          
            .data-table-container {
                width: 100%;
                margin: 20px auto;
                max-height: 60vh;
                overflow-y: auto;
                overflow-x: auto;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
                border-radius: 8px;
                background: white;
                padding: 10px;
            }
            
            .data-table-container table {
                width: 100%;
                border-collapse: collapse; /* Ensures borders collapse into one */
            }
            
            .data-table-container th,
            .data-table-container td {
                padding: 12px;
                text-align: left;
                border: 1px solid #ddd; /* Add borders to all cells */
                background-color: white; /* Set background to white for all cells */
            }
            
            .data-table-container th {
                background-color: #f2f2f2; /* Light gray background for headers */
            }
            
         
            .data-table-container tr:hover {
                background-color: white; /* Keep the hover effect white */
            }
            
            
            .data-table-container tr {
                background-color: white; /* Force all rows to have a white background */
            }

            .modal-content {
                background-color: #fefefe;
                margin: 15% auto;
                padding: 20px;
                border: 2px solid black;
                width: 80%;
                max-width: 600px;
                text-align: center;
            }
            #shareLinkModal {
                position: fixed;
                z-index: 1;
                left: 0;
                top: 0;
                width: 100%;
                height: 100%;
                overflow: auto;
                background-color: rgb(0,0,0);
                background-color: rgba(0,0,0,0.4);
            }
            .close {
                color: #aaa;
                float: right;
                font-size: 28px;
                font-weight: bold;
            }
            .close:hover,
            .close:focus {
                color: black;
                text-decoration: none;
                cursor: pointer;
            }
        </style>

        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

    <body>
        {% block navbar %}{% include "navbar.html" %}{% endblock %}
        {% comment %} {% include "messages.html" %} {% endcomment %}
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <div class="jumbotron mt-5">
            {% block content %}{% endblock %}
        </div>
    
        <div class="container footer-container">
            <div class="row"></div>
            <hr>
            
            <footer>
                <p>&copy; Data Vis 2024</p>
            </footer>
        </div>

        {% block scripts %}
        <script src="{% static 'js/analytics.js' %}"></script>
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

sales_analysis/sales_analysis/templates/messages.html
{% if messages %}
    <ul class="message-list">
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <li class="alert alert-success">{{ message }}</li>
            {% elif message.tags == 'error' %}
                <li class="alert alert-danger">{{ message }}</li>
            {% elif message.tags == 'info' %}
                <li class="alert alert-info">{{ message }}</li>
            {% elif message.tags == 'warning' %}
                <li class="alert alert-warning">{{ message }}</li>
            {% endif %}
        {% endfor %}
    </ul>
{% endif %}

sales_analysis/sales_analysis/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        {% comment %} <a class="navbar-brand" href="{% url 'home' %}">DataVIS</a> {% endcomment %}

        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/logo2.png' %}" alt="Logo" style="height: 50px; width: 70px">  
        </a>

        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'upload' %}">Upload files</a>

            {% with latest_sales_data=user.salesdata_set.last %}
                {% if latest_sales_data %}
                    <a class="navbar-brand" href="{% url 'dashboard' file_id=latest_sales_data.id %}" style="text-decoration: none;">Dashboard</a>
                {% endif %}
            {% endwith %}

            <span class="navbar-brand" style="color: aqua;">Hello, {{ user.get_username }}</span>
   
            <form method="POST" action="{% url 'logout' %}?next={{ home }}">
                {% csrf_token %}
                <button class="btn btn-info" type="submit">Press to Logout</button> 
            </form>
        {% else %}
            <a class="navbar-brand" href="{% url 'login' %}?next={% url 'upload' %}">Upload files</a>
            <div>
                <a class="btn btn-danger" href="{% url 'signup' %}">Sign up</a>
                <a class="btn btn-primary" href="{% url 'login' %}?next={{ upload }}">Log in</a>
            </div>
        {% endif %}
    </div>
</nav>